In [2]:
import tensorflow as tf
tf.__version__

'2.5.0'

In [8]:
scalar=tf.constant(1,2)
scalar

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [12]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a
a.shape

(2, 3)

In [11]:
tf_array=tf.constant(a)
tf_array

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [15]:
tf_array1=tf.constant([1,2,3,4])
tf_array1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [19]:
tf_array2=tf.constant([1,2,3,4,5,6,7,8])
tf_array2

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8])>

In [25]:
tf_array3=tf.constant(tf_array2,shape=[2,2,2])
tf_array3

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

In [30]:
tf_array3=tf.cast(tf_array3,dtype=tf.float32)
tf_array3

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]], dtype=float32)>

In [31]:
tf_array3.ndim

3

In [32]:
vector=tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [33]:
vector.ndim

1

In [35]:
vector=tf.constant([[1,2],[2,3]])
vector.ndim

2

In [36]:
vector2=tf.constant([[1.,2.],[3.,4,],[5.,6.],[7.,8.],[9.,10.]])
vector2.ndim

2

In [42]:
vector2=tf.cast(vector2,dtype=tf.float32)
vector2

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]], dtype=float32)>

In [44]:
another_matrix = tf.constant([10., 7.,3., 2.,8., 9.], shape=[3,2],dtype=tf.float16) # specify the datatype with 'dtype'
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [45]:
###combination of int32 and float16 

another_matrix = tf.constant([10., 7.,3, 2.,8., 9.], shape=[3,2]) # specify the datatype with 'dtype'
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [46]:
###combination of int32 and float16 

another_matrix = tf.constant([10, 7.,3, 2,8, 9], shape=[3,2]) # specify the datatype with 'dtype'
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [47]:
another_matrix.ndim

2

In [50]:
tensor_df=tf.constant([[[1,2],[1,2]],[[1,2],[1,2]],[[1,2],[1,2]]])
tensor_df.shape

TensorShape([3, 2, 2])

In [51]:
tensor_df

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]]])>

In [57]:
#constants are immutable, variables are mutable

unchangable = tf.constant([1,2])
changable=tf.Variable([3,4])


changable[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([8, 4])>

In [58]:
unchangable[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [62]:
a = tf.Variable([2.0, 3.0])
# This will keep the same dtype, float32
b=a.assign([1, 2]) 
# Not allowed as it resizes the variable: 
b

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [63]:
try:
  a.assign([1.0, 2.0, 3.0])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Cannot assign to variable Variable:0 due to variable shape (2,) and value shape (3,) are incompatible


In [64]:
a=tf.Variable([1,2])
b=tf.Variable(a)
print(a)
print(b)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>


In [69]:
print(a.assign([2,3]))

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>


In [71]:

print(a.assign_add([2,3]))
print(a.assign_sub([4,6]))

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([4., 6.], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>


In [72]:
a = tf.Variable([2.0, 3.0])
# Create b based on the value of a
b = tf.Variable(a)
a.assign([5, 6])

# a and b are different
print(a.numpy())
print(b.numpy())

# There are other versions of assign
print(a.assign_add([2,3]).numpy())  # [7. 9.]
print(a.assign_sub([7,9]).numpy())  # [0. 0.]

[5. 6.]
[2. 3.]
[7. 9.]
[0. 0.]


In [77]:
random_1 = tf.random.Generator.from_seed(42) 
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [78]:
# Create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Check the tensors and see if they are equal
random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [1]:
import tensorflow as tf

# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4], 
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [2]:
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

It's due to rule #4 of the tf.random.set_seed() documentation.

"4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

tf.random.set_seed(42) sets the global seed, and the seed parameter in tf.random.shuffle(seed=42) sets the operation seed.

Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."

In [3]:
import tensorflow as tf
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [9]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [10]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [13]:
tf.zeros(shape=(3,2,2))

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [15]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[4, 3, 2]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],
 
        [[ 7,  8],
         [ 9, 10],
         [11, 12]],
 
        [[13, 14],
         [15, 16],
         [17, 18]],
 
        [[19, 20],
         [21, 22],
         [23, 24]]])>)

In [16]:
tf.zeros(shape=(4,3,2,2))

<tf.Tensor: shape=(4, 3, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [17]:
tf_zeros=tf.zeros(shape=(4,3,2,2))
tf_zeros.ndim, tf_zeros.shape, tf.size(tf_zeros).numpy()

(4, TensorShape([4, 3, 2, 2]), 48)

In [18]:
# Get various attributes of tensor
print("Datatype of every element:", tf_zeros.dtype)
print("Number of dimensions (rank):", tf_zeros.ndim)
print("Shape of tensor:", tf_zeros.shape)
print("Elements along axis 0 of tensor:", tf_zeros.shape[0])
print("Elements along last axis of tensor:", tf_zeros.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(tf_zeros).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (4, 3, 2, 2)
Elements along axis 0 of tensor: 4
Elements along last axis of tensor: 2
Total number of elements (2*3*4*5): 48


In [20]:

# Get the dimension from each index except for the final one
tf_zeros[:2, :2, :2, :]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [22]:
rank_2_tensor=tf.constant([[1,2],[3,4]])

In [23]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [24]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[1],
         [2]],
 
        [[3],
         [4]]])>)

In [25]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [41]:
tensor=tf.constant([[1,2],[3,4]])
tensor=tensor+10

In [42]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]])>

In [43]:
tensor[0]=tensor[0].assign(1)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [44]:
tensor=tensor-10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [45]:
tensor=tensor+10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]])>

In [46]:
tensor=tensor*10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]])>

In [47]:

tensor=tf.multiply(tensor,10)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1100, 1200],
       [1300, 1400]])>

In [49]:

tensor=tf.add(tensor,1)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1101, 1201],
       [1301, 1401]])>

In [53]:

tensor=tf.subtract(tensor,10)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1091, 1191],
       [1291, 1391]])>

In [55]:

tensor=tf.divide(tensor,1)
tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1091., 1191.],
       [1291., 1391.]])>

In [56]:
tensor=tf.matmul(tensor,tensor)
tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2727862., 2956062.],
       [3204262., 3472462.]])>

In [58]:
tensor=tf.constant([[1,2],[3,4]])
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]])>

In [59]:

# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [60]:
# Try to matrix multiply them (will error)
X @ Y

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

In [64]:
tensor2=tf.constant([[1,2],[3,4],[5,6]])
tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [61]:
tensor1=tf.constant([[1,2,3],[3,4,5]])
tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]])>

In [62]:
tf.reshape(tensor1, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 3],
       [4, 5]])>

In [67]:

# Try matrix multiplication with reshaped Y
tensor2 @ tf.reshape(tensor2, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])>

In [68]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(tensor2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [70]:
a = tf.constant([1.7,1.4])
b=tf.constant([1,7])
print(a,b)
tf.cast(a,dtype=tf.int32), tf.cast(b,dtype=tf.float32)

tf.Tensor([1.7 1.4], shape=(2,), dtype=float32) tf.Tensor([1 7], shape=(2,), dtype=int32)


(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1])>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>)

In [71]:
# Create tensor with negative values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [73]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [82]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50),shape=(5,10))
E

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[20, 15, 43, 95, 35, 61, 99, 50, 38, 36],
       [28, 50, 31, 78, 40, 55, 65, 49, 24, 94],
       [40, 42, 50, 34,  6, 99, 98, 38, 89, 65],
       [28, 52, 63, 76, 86, 33, 68, 49, 15, 94],
       [29, 40, 97, 94, 89, 29, 83, 87, 99, 21]])>

In [83]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [84]:
# Find the minimum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [86]:
# Find the minimum
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=55>

In [89]:
# Find the minimum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2799>

In [94]:
# Find the minimum
E=tf.cast(E,dtype=tf.float32)
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=755.8596>

In [95]:
# Find the minimum
E=tf.cast(E,dtype=tf.float32)
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=27.4929>

In [93]:
x = tf.constant([[1., 2.], [3., 4.]])
tf.math.reduce_variance(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.25>

In [97]:
E

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[20., 15., 43., 95., 35., 61., 99., 50., 38., 36.],
       [28., 50., 31., 78., 40., 55., 65., 49., 24., 94.],
       [40., 42., 50., 34.,  6., 99., 98., 38., 89., 65.],
       [28., 52., 63., 76., 86., 33., 68., 49., 15., 94.],
       [29., 40., 97., 94., 89., 29., 83., 87., 99., 21.]], dtype=float32)>

In [98]:
# Create a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.8761021 , 0.69000725, 0.55209487, 0.17568437, 0.5702613 ,
       0.31465516, 0.25491505, 0.12996479, 0.4205616 , 0.74487137,
       0.92255041, 0.27917103, 0.79635952, 0.45284913, 0.50728944,
       0.26205216, 0.15273192, 0.48542192, 0.48944313, 0.85925637,
       0.95675184, 0.05531289, 0.23177367, 0.92652747, 0.0080264 ,
       0.21336269, 0.02542476, 0.49152385, 0.13952236, 0.05646846,
       0.55046377, 0.75473374, 0.74723756, 0.77316741, 0.06786912,
       0.46714927, 0.33210434, 0.52855875, 0.27960009, 0.91895156,
       0.80613248, 0.44580364, 0.92895853, 0.33438756, 0.78515078,
       0.33597468, 0.62141356, 0.47571222, 0.93889463, 0.98132952])>

In [99]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [100]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=24>

In [101]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 49
The maximum value of F is: 0.9813295243583576
Using tf.argmax() to index F, the maximum value of F is: 0.9813295243583576
Are the two max values the same (they should be)? True


In [102]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [103]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

In [104]:

# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [105]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

In [106]:

# Create a new tensor
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [107]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [108]:

# Find the squareroot (will error), needs to be non-integer
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [109]:

# Change H to float32
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [110]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [111]:
# Create a variable tensor
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [112]:

# Create a variable tensor
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [113]:
# Assign the final value a new value of 50
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [114]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [116]:
I.assign_add([1,2,3,4,5])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 1,  3,  5,  7, 55])>

We've seen some examples of tensors interact with NumPy arrays, such as, using NumPy arrays to create tensors.

Tensors can also be converted to NumPy arrays using:

np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).
tensor.numpy() - call on a tensor to convert to an ndarray.
Doing this is helpful as it makes tensors iterable as well as allows us to use any of NumPy's methods on them.

In [117]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [119]:
 #Convert tensor J to NumPy with np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [120]:
# Convert tensor J to NumPy with .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [121]:
# Convert tensor J to NumPy with .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)


By default tensors have dtype=float32, where as NumPy arrays have dtype=float64.

This is because neural networks (which are usually built with TensorFlow) can generally work very well with less precision (32-bit rather than 64-bit).

In [122]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)


Using @tf.function
In your TensorFlow adventures, you might come across Python functions which have the decorator @tf.function.

If you aren't sure what Python decorators do, read RealPython's guide on them.

But in short, decorators modify a function in one way or another.

In the @tf.function decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with @tf.function, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

In [123]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [124]:

# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>


If you noticed no difference between the above two functions (the decorated one and the non-decorated one) you'd be right.

Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.